version: '3'

services:
  frontend:
    container_name: 'vue-chat-frontend'
    build: ./docker/frontend
    ports:
      - 8080:8080
    volumes:
      - .:/frontend
    tty: true
  
  backend:
    container_name: 'vue-chat-backend'
    build: ./docker/backend
    ports:
      - 8081:8081
    volumes:
      - .:/backend
    tty: true